#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

// The speed at which the robot moves.
int K_SPEED = 120;
// The threshold is 1302 because when the sensor reads the value more than 1302, it means the sensor is detecting a dark light and vice-versa.
int K_THRESHOLD = 1302;
// The distance from which the robot should start slowing down the speed.
int K_SONARTHRESHOLD = 50;
// The distance before which the robot should stop.
int K_STOP_DISTANCE = 5;

// Moves the robot forward.
void moveForward(){
		motor[rightMotor] = K_SPEED;
		motor[leftMotor] = K_SPEED;
}

// Turns the robot left.
void turnLeft(){
		motor[leftMotor] = -K_SPEED;
		motor[rightMotor] = K_SPEED;
}

// Turns the robot right.
void turnRight(){
		motor[leftMotor] = K_SPEED;
		motor[rightMotor] = -K_SPEED;
}

// Stops the robot gradually.
void slowStop(){
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while (true) {
		// Get the distance of robot from the wall.
		int currentDistance = SensorValue[sonarSensor];

		// Get the remaining distance.
		int remainingDistance = currentDistance - K_STOP_DISTANCE;

		// Calculate the required speed at this specific second of time.
		float speed = (K_SPEED) * ((float)remainingDistance / K_SONARTHRESHOLD);

		// Break the loop once the speed required becomes 0.
		if(speed == 0) break;

		// Update the speed of the robot.
		motor[rightMotor] = (int)speed;
		motor[leftMotor] = (int)speed;
	}

	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}

task main() {

	// Move the robot forward till the starting line.
	moveForward();
	wait1Msec(1000);

	// Start the loop till the sensor valie of the robot reaches the threshold.
	while (SensorValue[sonarSensor] != K_SONARTHRESHOLD) {

		// Get the value of all the sensors.
		int leftSensor = SensorValue[leftLineFollower];
		int centerSensor = SensorValue[centerLineFollower];
		int rightSensor = SensorValue[rightLineFollower];

		// Keep moving the robot if the value of all the sensors are more than the threshold.
		if (leftSensor > K_THRESHOLD && centerSensor > K_THRESHOLD && rightSensor > K_THRESHOLD) {
			moveForward();
		}
		else if (rightSensor > K_THRESHOLD) {
			turnRight();
		}
		else if (leftSensor > K_THRESHOLD) {
			turnLeft();
		}
		else {
			moveForward();
		}
	}

	// Stop the robot gradually.
	slowStop();
}
