#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

// This speed at which the robot moves.
#define K_SPEED 127
// The threshould before which the robot stops incase of any object/wall in the front.
#define K_SONARTHRESHOLD 25
// The time for which the robot should turn to make a right/left turn.
#define K_TURN_TIME 633

// Moves the robot forward.
void moveForward(){
		motor[rightMotor] = K_SPEED;
		motor[leftMotor] = K_SPEED;
}

// Turns the robot's face to the left side.
void turnLeft(){
	// Turn on both the wheels on full speed.
	motor[rightMotor] = 127;
	motor[leftMotor]  = -127;
	// Keep the wheels on for few seconds.
	wait1Msec(K_TURN_TIME);
	// Turn off both the wheels.
	motor[rightMotor] = 0;
	motor[leftMotor]  = 0;
}

// Turns the robot's face to the right side.
void turnRight(){
	// Turn on both the wheels on full speed.
	motor[leftMotor]  = 127;
	motor[rightMotor] = -127;
	// Keep the wheels on for few seconds.
	wait1Msec(K_TURN_TIME);
	// Turn off both the wheels.
	motor[rightMotor] = 0;
	motor[leftMotor]  = 0;
}

task main() {

	while(true){
		// Keep moving the robot forward untill there is a wall in the front.
		if(SensorValue[sonarSensor] != K_SONARTHRESHOLD) {
			moveForward();
			continue;
		}

		// Turn the robot left.
		turnLeft();
		wait1Msec(200);
		// Calculate the space left between the robot and the nearest wall in the front.
		int leftWallDistance = SensorValue[sonarSensor];

		// Turn the robot right.
		turnRight();
		wait1Msec(200);
		turnRight();
		wait1Msec(200);
		// Calculate the space left between the robot and the nearest wall in the front.
		int rightWallDistance = SensorValue[sonarSensor];

		wait1Msec(2000);

		// Turn the robot in the direction where the wall is farther.
		if(leftWallDistance > rightWallDistance) {
			turnLeft();
			wait1Msec(200);
			turnLeft();
			wait1Msec(200);
		}
		// Continue the loop.
	}
}
